[package]
name = "proc-hexdump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
nix = "0.26.1"
proc-maps = "0.3.0"
sysinfo = "0.27.6"
